### ISSUE TITLE
acme-lsp crashes the latest gopls

### ISSUE THREAD

**Issue by mariusae** [fhs/acme-lsp#16]
I've [filed an issue](https://github.com/golang/go/issues/34212) in the the golang tracker with details. For now, recommend using gopls at hte prior commit:

<pre>
$ GO111MODULE=on go get golang.org/x/tools/cmd/gopls@238129aa638afb6cf8cf56a290487ddd93c2fad7
</pre>

**Comment by fhs** [comment]
What version of acme-lsp are you using? I recommend the latest tagged release (v0.6.1). `master` might be unstable right now because I'm making some big changes.

**Comment by mariusae** [comment]
I'm using `@latest`. I'll try with with a tagged release. fwiw, from the [golang issue](https://github.com/golang/go/issues/34212#issuecomment-530054040):

> Looks like acme-lsp is sending a didopen call before initialized, which it is not allowed to do.
We would have survived that before, although there would have been subtle bugs.
There is still a bug we should fix here (crashes are never ok) but if I am right then the fix is to start obeying the spec and rejecting all messages before the initialize handshake is done, in which case acme-lsp is still going to be broken until that is fixed as well.
