### ISSUE TITLE
Lassist is awesome but not mentioned in README

### ISSUE THREAD

**Issue by ilanpillemer** [fhs/acme-lsp#22]
I really love Lassist and how it updates its own window as you type to provide context relevant information...  but I only discovered it accidentally. Perhaps its existence should be mentioned in the README?

**Comment by fhs** [comment]
`L assist` is sort of experimental feature that I never ended up using much personally. I found it too distracting, but maybe I should give it another try.

Of course, I'll mention it in the readme if other users find it useful. Feedback is always welcome.
