### ISSUE TITLE
Error starting clojure-lsp

### ISSUE THREAD

**Issue by scotts777** [fhs/acme-lsp#28]
Trying to start up acme-lsp with a config.toml file that is specifying the clojure-lsp server.  Running on Mac OS X 10.15.2

My PATH contains the location of clojure-lsp.   Typing clojure.lsp in the shell runs it successfully.  I have used this lsp server with VSCode and Neovim successfully.

The error I am getting is:
failed to create file manager: failed to execute language server: fork/exec /usr/local/clojure-lsp/clojure-lsp: exec format error

That is the correct location to clojure-lsp.  There are no log messages in the LogFile or StderrFile or the clojure-lsp log.

Config is:
`ProxyNetwork = "unix"
ProxyAddress = "/tmp/ns.ses.:0/acme-lsp.rpc"
AcmeNetwork = "unix"
AcmeAddress = "/tmp/ns.ses.:0/acme"
WorkspaceDirectories = ["/Users/ses/Projects/Clojure/finance"]
RootDirectory = "/"
FormatOnPut = true
CodeActionsOnPut = ["source.organizeImports"]

[Servers]
  [Servers.clojure]
    Command = ["clojure-lsp"]
    Address = ""
    StderrFile = "/Users/ses/Library/Caches/acme-lsp/clojure.stderr.log"
    LogFile = "/Users/ses/Library/Caches/acme-lsp/clojure.log"
    [Servers.clojure.Options]
      hoverKind = "FullDocumentation"

[[FilenameHandlers]]
  Pattern = "(\\.deps)|(\\.clj)$"
  ServerKey = "clojure"`

**Comment by fhs** [comment]
`clojure-lsp` is doing something clever to make it execute in unix shells:
```
$ sed 4q clojure-lsp 
:;exec java -Xmx1g -server -Dclojure-lsp.version=0.1.0-SNAPSHOT -jar $0 "$@"
@echo off
java -Xmx1g -server -Dclojure-lsp.version=0.1.0-SNAPSHOT -jar "%~f0" %*
goto :eof
```
This will probably work:
```
 Command = ["sh", "-c", "clojure-lsp"]
```
(Note: `rc -c clojure-lsp` doesn't work.)

**Comment by scotts777** [comment]
yep worked.  Thanks for the assistance.  This looks like you did a very nice job with the lsp feature.  Good work.
