### ISSUE TITLE
question: support for projects without a go.mod?

### ISSUE THREAD

**Issue by mpl** [fhs/acme-lsp#3]
As per the README: "where mod1 and mod2 are module directories with a go.mod file."
Does this mean that L won't ever support projects without a go.mod and/or with GO111MODULE=off ?
If yes, is that due to a limitation of gopls?

P.S: I've just had a quick try and already found what I think are two obvious problems, but not sure I should open issues as you probably are already aware of them:

1) apparently the argument to -workspaces needs to be an absolute path. I've tried with a (valid) relative path, and things didn't seem to work.
2) 'L def' seems to result in an address like /some/path:line:column , which does not seem to open. If I remove the :column , it works. Or maybe I'm missing some plumb rules that are not by default in p9p acme?

Let me know if you want me to open issues for the above.

**Comment by fhs** [comment]
> As per the README: "where mod1 and mod2 are module directories with a go.mod file."
> Does this mean that L won't ever support projects without a go.mod and/or with GO111MODULE=off ?
> If yes, is that due to a limitation of gopls?

Yes, it's a limitation of `gopls`. You can always use [`go-langserver`](https://github.com/sourcegraph/go-langserver) for non-module projects, but I don't know how much longer it'll be maintained. Everyone is moving to modules because module mode will be turned on by default in [Go 1.13](https://blog.golang.org/modules2019), and GOPATH mode will be deprecated.

> P.S: I've just had a quick try and already found what I think are two obvious problems, but not sure I should open issues as you probably are already aware of them:
> 
> 1. apparently the argument to -workspaces needs to be an absolute path. I've tried with a (valid) relative path, and things didn't seem to work.
> 2. 'L def' seems to result in an address like /some/path:line:column , which does not seem to open. If I remove the :column , it works. Or maybe I'm missing some plumb rules that are not by default in p9p acme?
> 
> Let me know if you want me to open issues for the above.

Don't worry -- I'll have these fixed by end of the day.

**Comment by mpl** [comment]
Understood, thanks.

**Comment by fhs** [comment]
I fixed those two issues.

The plumbing issue may have been caused by how reloading plumber rules is broken: https://github.com/9fans/plan9port/issues/256. In any case, we don't depend on those rules anymore.

**Comment by mpl** [comment]
nice
