### ISSUE TITLE
Support specify configuration file through cmdline

### ISSUE THREAD

**Issue by tw4452852** [fhs/acme-lsp#38]
It will be handy if we can override the default configuration file path by something like this:

```
acme-lsp -c /path/to/config.toml
```

**Comment by fhs** [comment]
Duplicate of #21.

I think it'll be better to add an environment variable (e.g. `ACME_LSP_CONFIG`) which specified the location of the config file. Both the `acme-lsp` command and `L` command needs to use the same config file, and I can imagine having the specify `-c` flag to `L` will be inconvenient.
