### ISSUE TITLE
acmefocused not working

### ISSUE THREAD

**Issue by arturfabriciohahaedgy** [fhs/acme-lsp#53]
I followed the usage present in [the acmefocused page](https://pkg.go.dev/github.com/fhs/acme-lsp/cmd/acmefocused) but every time I do `dial $(namespace)/acmefocused` it returns this:
`dial: dial: malformed address`
As far as I know, this is the same message that happens when you insert an address that doesn't exist, but if I `cd` into it with `cd $(namespace) `and do a `ls`, acmefocused does appear:
```
srwxr-xr-x 0 artur 31 Dec 10:17 acme
srwxr-xr-x 0 artur 31 Dec 10:17 acmefocused
srwxr-xr-x 0 artur 31 Dec 09:39 font
srwxr-xr-x 0 artur 31 Dec 09:40 plumb
```
If I'm doing something wrong, I ask you for clarification...

**Comment by fhs** [comment]
Apologies for the late response.

You need to specify a protocol in the dial string:
```
dial 'unix!'$(namespace)/acmefocused
```
I've corrected the example in the documentation.
