### ISSUE TITLE
Automatically launch acme-lsp at acme startup

### ISSUE THREAD

**Issue by lobre** [fhs/acme-lsp#63]
I am relatively new to Acme, so I am not aware if there is a principle of "autostart".

Can Acme automatically launch acme-lsp when it starts? If so, how? If not, what is your current workflow to start acme-lsp?

Thanks and sorry for the n00b question!

**Comment by fhs** [comment]
See the acme(1) man page regarding `Dump` and `Load` command and the `-l` flag.

It should be possible to start acme-lsp from the dump file but we don't support it yet. There is issue #15 open for that.
