### ISSUE TITLE
acme-lsp doesn't play well with editinacme

### ISSUE THREAD

**Issue by mariusae** [fhs/acme-lsp#9]
When acme-lsp is running, [editinacme](https://github.com/9fans/go/tree/master/acme/editinacme) does not appear to work properly. (It also relies on the use of editor events.) Editinacme can successfully launch editor windows, but does not detect window delete events until after acme-lsp is killed. I haven't had the time to look into it yet, but it may be that acme-lsp is blocking propagation of those events in some way.

**Comment by fhs** [comment]
acme-lsp wasn't closing the file server file, which was preventing acme from writing the del event to log file. I'm not sure if acme is entirely correct in not sending the del event in this case, but acme-lsp should close the files anyway.
